//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpdesk.ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentarz
    {
        public int IdKomentarza { get; set; }
        public string Tresc { get; set; }
        public System.DateTime DataDodania { get; set; }
        public int IdZgloszenia { get; set; }
        public string UzytkownikId { get; set; }
    
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Zgloszenie Zgloszenie { get; set; }
    }
}
