//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpdesk.ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgloszenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zgloszenie()
        {
            this.Komentarz = new HashSet<Komentarz>();
        }
    
        public int IdZgloszenia { get; set; }
        public string Temat { get; set; }
        public string Tresc { get; set; }
        public string Grafika { get; set; }
        public string Plik { get; set; }
        public int IdPriorytet { get; set; }
        public int IdKategorii { get; set; }
        public int IdStatusu { get; set; }
        public System.DateTime DataDodania { get; set; }
        public System.DateTime DataZakonczenia { get; set; }
        public System.DateTime DataAktualizacji { get; set; }
        public string UzytkownikId { get; set; }
        public string PracownikId { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komentarz> Komentarz { get; set; }
        public virtual Priorytet Priorytet { get; set; }
        public virtual Status Status { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
    }
}
